### ISSUE TITLE
server crashes when loading page in browser

### ISSUE THREAD

**Issue by jonatjano** [fmdkdd/sparkets#2]
Hi !
I wanted to try your game so I installed has told in Readme,
launched using `npm start`
then when I browser to `127.0.0.1:12345` I have this error : 
```
_http_outgoing.js:476
    throw err;
    ^

TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"
    at storeHeader (_http_outgoing.js:411:5)
    at processHeader (_http_outgoing.js:406:3)
    at ServerResponse._storeHeader (_http_outgoing.js:311:11)
    at ServerResponse.writeHead (_http_server.js:270:8)
    at /media/Windows/Users/jonat/Documents/jeux/sparkets/build/server/httpServer.js:101:13
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
error Command failed with exit code 1.
```
This is a fatal error killing the server.

Tested using both Firefox and Chrome

My Firefox user-agent : `Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0`
My Chrome user-agent : `"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"`

**Comment by fmdkdd** [comment]
Oh wow, thanks for noticing!  I seem to have left things in a bad state last time, as I was ditching sockets.io to use the ws library directly.

The lobby page is indeed broken, but if you restart the server you should be able to play by going to http://localhost:12345/play/#1.  All players connecting to this URL should see each other.

There's quite a bit of cleanup to do, like updating dependencies and finishing the move to `ws`.  Help is welcome ;)

**Comment by fmdkdd** [comment]
I've updated the console message to direct to the `/play/` URL, since now I remember that we were in the process of ditching all that lobby stuff.

Unfortunately, that means that right now if you want to tweak the parameters (like number of bots to play against), you need to edit `src/server/prefs.coffee` directly, `make` and run again.

I've tested it and it should be playable now.  Have fun!
